### PR TITLE
Delegate's Updates

### PR DESCRIPTION
**Pull request by Hipogeo**
@Prose11

### CODE REVIEW

**Comment by mkrorbrkr** [comment]
@Hipogeo some of these numbers don't seem to match the spreadsheet. Are you absolutely sure they're correct?

**Comment by Hipogeo** [comment]
Hey mkr! Thats odd... I take them right from the sheet

**Comment by Hipogeo** [comment]
For Poll outcome I take the Combined Poll outcome

**Comment by mkrorbrkr** [comment]
So for example, looking at the sheet just now: MakerMan (0x22d5294a23d49294Bf11D9db8bEda36e104ad9b3) has a combined_output for Participation of 79.59% but this PR has it at 72.94%

**Pull request closed without merging**
