### PR TITLE
Polls 2020 09 21

### PR DESCRIPTION
**Pull request by LongForWisdom**
Greenlight polls, MIPs Bundle for September.

### CODE REVIEW

**Comment by LongForWisdom** [comment]
Note that the MIPs Bundle still needs a discussion link filled in. @CPSTL if you could add it (there are two places in the file, search for '$')

**Review by CPSTL — COMMENTED** [review]
Unfortunately, I don't have edit access to this repo/PR. However, here is the link to the Weekly MIPs update highlighting the proposals that will be moving to the Monthly MIPs Governance Poll on Monday, September 21: https://forum.makerdao.com/t/weekly-mips-update-15/4243

**Comment by LongForWisdom** [comment]
Added the required link.

**Comment by LongForWisdom** [comment]
I'm not sure that @CPSTL can actually approve. But If you could check the content Charles, maybe @derek-flossman can approve?

**Review by derek-flossman — APPROVED** [review]
👍 lgtm

**Pull request merged**
