### PR TITLE
Community Executive Copy 202-02-26

### PR DESCRIPTION
**Pull request by LongForWisdom**
Executive Copy

### CODE REVIEW

**Comment by LongForWisdom** [comment]
@prose11 would also appreciate you taking a look.

**Comment by prose11** [comment]
On it!

**Review by prose11 — APPROVED** [review]
Read through, tested links and put through Grammerly. Looks good to me, nice work @LongForWisdom !

**Review by derek-flossman — COMMENTED** [review]
lgtm!

**Pull request merged**
