### PR TITLE
Having a go at re-working the executive vote / proposal template.

### PR DESCRIPTION
**Pull request by LongForWisdom**
Not sure if this is better, or if so, how much.

### CODE REVIEW

**Comment by LongForWisdom** [comment]
@blimpa any thoughts?

**Comment by blimpa** [comment]
I like it.  How do you feel about having an index with anchored links at the top?

* Executive Summary
** Executive Action Description 1
[...]

* Proposal Details
** Executive Entry 1
[...]

**Comment by LongForWisdom** [comment]
Hmmm, not sure about a separate index. I might be misunderstanding you. Maybe the executive summary entries can link to the proposal details part further down in the document? Maybe that's what you meant.

**Comment by blimpa** [comment]
Having Executive Summary entries link to their corresponding Proposal Details entries is a great idea, yes. I meant having an index at the top though, if only for very long votes with many complex proposals maybe?

**Comment by LongForWisdom** [comment]
Needs something about the GSM too.

**Comment by LongForWisdom** [comment]
Aight, added something about the GSM Pause Delay. Going to use this for this week and see if there are any comments.

**Pull request merged**
