### PR TITLE
Scroll CTA, Mobile Nav Fix

### PR DESCRIPTION
**Pull request by MaximumCrash**
### Attention (CC)
@twblack88  @lesamone @shea-fitz 

## Summary of changes
- Added ScrollCTA element to site layout with sessionStorage check and scroll distance checks. 
- Fixes Mobile Nav links not closing the menu. 
- Merged in Master
## Relevant Context

- Feature: #1012 

## How Has This Been Tested?
Locally

## Further comments
This element is not controllable via any mdx files. This has been hard coded into the site_layout file. Any changes or tweaks to copy/links should be made in that file and stakeholders MUST be made aware of such changes. 

If you don't want your page to have the scrollCTA just add `hideScrollCTA: true` to your frontmatter. 

--- 
## Types of changes

- [ ] Content edit, File upload, content addition
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Technical Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [x] Yes
- [ ] No

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added/changed necessary documentation (if appropriate)
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by twblack88** [comment]
So, to remove it from any pages we just go into the YAML and add `hideScrollCTA: true`

Nice!

**Comment by twblack88** [comment]
I built locally to play around and man the `onscroll` is tight

However I found a weird bug, I think the mdx_layout and  site_layout files aren't playing nice. Maybe something is prioritizing the CTA over boxes and all the components? thoughts @MaximumCrash ?

The bottom of a learn page should be chocolate boxes but they're just text:
Screen Shot 2020-11-28 at 11 06 01 AM

an image on a landing page decided to become, well, huge 🤣 
Screen Shot 2020-11-28 at 11 06 27 AM

same with collateral and risk landing, big old landing image. 
Screen Shot 2020-11-28 at 11 06 30 AM

another example, the funding page should have infoblock at the bottom with some lists embedded. But they just want to be text instead. 👀 
Screen Shot 2020-11-28 at 11 08 28 AM

**Comment by MaximumCrash** [comment]
> I built locally to play around and man the `onscroll` is tight
> 
> However I found a weird bug, I think the mdx_layout and site_layout files aren't playing nice. Maybe something is prioritizing the CTA over boxes and all the components? thoughts @MaximumCrash ?
> 
> The bottom of a learn page should be chocolate boxes but they're just text:
> Screen Shot 2020-11-28 at 11 06 01 AM
> 
> an image on a landing page decided to become, well, huge 🤣
> Screen Shot 2020-11-28 at 11 06 27 AM
> 
> same with collateral and risk landing, big old landing image.
> Screen Shot 2020-11-28 at 11 06 30 AM
> 
> another example, the funding page should have infoblock at the bottom with some lists embedded. But they just want to be text instead. 👀
> Screen Shot 2020-11-28 at 11 08 28 AM

@twblack88 I haven't been able to replicate your images on dev environment or served envrionments. From what I can tell on your images it could be a server side rendering hiccup (this can happen on dev environments). The CTA is fixed position and it's functionality doesn't intersect the mdx_content being rendered. Can you try `yarn build && yarn serve` and then go to localhost:9000 to see if the issue is continuing to repeat itself on your end?

**Comment by lesamone** [comment]
Short description:

Bold: Help us make this site better!
Your feedback will help us improve the overall experience on this website. Do you have 10 minutes to spare?  
Button: Take Survey

**Review by twblack88 — APPROVED** [review]
🚀

**Pull request merged**
