### PR TITLE
FOR REVIEW: Modified delegate profile template for endgame structure.

### PR DESCRIPTION
**Pull request by LongForWisdom**

### CODE REVIEW

**Review by adamgoth — APPROVED** [review]
We've tested this against our updates for constitutional delegates and it works well

You can view it on goerli on this URL (it won't work on mainnet):

https://governance-portal-v2-mnxzanw24-dux-core-unit.vercel.app/delegates

**Review by adamgoth — COMMENTED** [review]
One suggestion we thought of -- can we add a new field in addition to `name` and `external_profile_url` for the CVC name? Maybe just `cvc`?

This will be helpful for categorizing delegates and make things like aggregating and filtering data much easier.

**Comment by LongForWisdom** [comment]
> One suggestion we thought of -- can we add a new field in addition to `name` and `external_profile_url` for the CVC name? Maybe just `cvc`?
> 
> This will be helpful for categorizing delegates and make things like aggregating and filtering data much easier.

Added `cvc_name`

**Comment by adamgoth** [comment]
> Added `cvc_name`

Great. Looking at it again, I'm also wondering if we should include `<CVC> -` in the name field if we have a separate field for it. In the UI, we can concatenate the `cvc_name` with the `name` field to get that value now. Thoughts?

**Comment by LongForWisdom** [comment]
> > Added `cvc_name`
> 
> Great. Looking at it again, I'm also wondering if we should include `<CVC> -` in the name field if we have a separate field for it. In the UI, we can concatenate the `cvc_name` with the `name` field to get that value now. Thoughts?

I can more or less set it up however. Just confirm with me on discord what you want.

**Pull request merged**
