### PR TITLE
Add Github Action to push to IPFS

### PR DESCRIPTION
**Pull request by rmulhol**
- on pushes to master, write governance/polls directory to IPFS

Example build:
Screen Shot 2020-06-26 at 3 49 11 PM

Result available at https://ipfs.io/ipfs/QmcqRPbXBxcq8Cw4u3h8zCGcjxKaEaBJ2DXf7rUMjqcA1X

### CODE REVIEW

**Comment by LongForWisdom** [comment]
How does this work in terms of IPFS's data availability? Is something setup to hold on to and provide this data?

**Comment by rmulhol** [comment]
> How does this work in terms of IPFS's data availability? Is something setup to hold on to and provide this data?

No, right now this just pushes the data to `ipfs.komputing.org`, but there's no pinning guaranteed. Would probably need to setup a host to pin the data and guarantee availability. That said, I figured this was still a step forward since if you have the data, you can verify it's integrity by confirming that it generates the same CID.

**Comment by LongForWisdom** [comment]
Seems like a cool thing to try at the very least. @ghettodev what are your thoughts?

**Comment by CPSTL** [comment]
> Seems like a cool thing to try at the very least. @ghettodev what are your thoughts?

If it helps, I merged the same implementation to the MIPs repo @ghettodev :)

**Comment by ghettodev** [comment]
Have some potentially dumb questions about IPFS I was hoping to have time to research in my own, but yolo... 

- Is the GH action the owner of the IPFS assets now?
- Will we be able to add to the directories if we decide to stop using GH in the future?
- Can anyone else add to them?
- What happens if GH or the 'actions' are down? Can we still get assets onchain?
- Does it make sense to link IPFS and GH in a single pipeline process or should they be behave as backups of each other?
- What are the plans to pin this stuff? Are we going to spin up some nodes?
- Shouldn't we add /votes as well?

**Comment by rmulhol** [comment]
> * Is the GH action the owner of the IPFS assets now?

Nobody really "owns" the assets, since they're written to IPFS - where they can be hosted/pinned by any number of nodes. That said, this action writes the files to a node hosted at `ipfs.komputing.org`. If that service disappears or the content is removed, then we'd depend on some other node having them. I'd say we don't want to count on the assets being available unless and until a someone is pinning them. That siad, we can always regenerate the exact same assets/CIDs so long as someone has access to the repo.

> * Will we be able to add to the directories if we decide to stop using GH in the future?

If we stop using GH, we would need to figure out another way to automate writing directories to IPFS. Can't think of any reason that wouldn't be possible. We can certainly add directories with or without GH.

> * Can anyone else add to them?

Anyone can write anything to IPFS, but you wouldn't be able to add to a specific asset without changing its CID (since the data is content-addressable, any modifications would yield a new content address).

> * What happens if GH or the 'actions' are down? Can we still get assets onchain?

If GH/actions are down, then this process probably won't be executed (or will be delayed) - the files won't be written to IPFS unless someone or some process puts them there. So long as they're on IPFS, you should be able to query for them from any IPFS node (e.g. `ipfs ls QmcqRPbXBxcq8Cw4u3h8zCGcjxKaEaBJ2DXf7rUMjqcA1X`).

> * Does it make sense to link IPFS and GH in a single pipeline process or should they be behave as backups of each other?

My thinking here is that putting it in one pipeline minimizes the effort needed for the data to make its way to both places. I would consider IPFS a potential backup for GH but not vice versa, since (afaik) we can't 100% guarantee the integrity of data shown on GH.

> * What are the plans to pin this stuff? Are we going to spin up some nodes?

That's an open question. My thinking is that if folks find this useful, they can either pin it themselves or drive a Foundation/community effort to pin it.

> * Shouldn't we add /votes as well?

Totally fine with me, that'd be trivial - just let me know if that's desired. We could even persist the whole repo with very little effort.

**Comment by LongForWisdom** [comment]
Including /votes seems sensible, no reason not to do that.

**Comment by LongForWisdom** [comment]
@rmulhol if you can add the votes folder to this, I'll get it reviewed and merged.

**Comment by rmulhol** [comment]
@LongForWisdom updated to push the whole `governance/` directory, which gives access to both `polls/` and `votes/` and lets you navigate between them from the same root: https://ipfs.io/ipfs/QmRVsyfwTUNWrkFGnKqxMFcNqhbU8LDK2VhCAJq2VLFfyQ

Let me know if it's important to isolate down to just `polls/` and `votes/` separately - figured it would be nice to have a single reference to the directory containing both, and supporting two paths seems to potentially require two Github actions.

**Comment by jparklev** [comment]
So cool :D


Yeah, this is super applicable to some of the work being done on linking on-chain votes with off-chain context/ documents. And it actually enables polling to be used the way it was designed to be from the start! (You can see the IPFS-intended [multihash](https://multiformats.io/multihash/) field  in the `PollCreated` event [here](https://github.com/makerdao/symbolic-voting/blob/c90ccedb47b530e240951a9b216677cf62b97289/src/polling.sol#L10).) Github was seen as a stop-gap until more research could be done into pinning and into the viability of IPFS long-term, but imo content addressing makes perfect sense for governance docs and I think it'd be great if we went this direction (putting document hashes in executive spells is probably on that path, too). 

Also if documents are pinned, the new gov portal could certainly be modified to do fetch directly from IPFS, which makes the potential for community/ 3rd party voting audits much greater.

Thinking about it now, my main 2 questions are 1) does anybody has an argument against using IPFS and 2) what the appetite is for running a node (from the foundation and from the community). I can float those questions internally to see about the foundation-side, but I also mention them here so that I'm a bit more beholden to anybody reading this to bring them up in other public spaces as well.

**Comment by rmulhol** [comment]
@LongForWisdom it worked 👍 

You can check out the Github Actions that ran after a build in [the Actions tab](https://github.com/makerdao/community/actions).

From there, you can click on a build and navigate to the [`build` link](https://github.com/makerdao/community/runs/928130345?check_suite_focus=true) on the left. 

Drop down the `Upload to IPFS` section, scroll to the bottom, and you'll find the CID. In this case, you can view the result at https://ipfs.io/ipfs/QmTn4bfuQeVftZtVTo178WX2vHy3oR8ghPPpPkTmigZK7d

**Pull request merged**
