### PR TITLE
Debate about stability fee calculation

### PR DESCRIPTION
**Pull request by Davidutro**
Temporary update. Still dealing with https://github.com/makerdao/community/issues/109

I reached out to Devs to ask if Chao is right about the specifics in the code. If he is right then some work on this FAQ might need to be done.

### CODE REVIEW

**Comment by ghettodev** [comment]
Is this ready for review or are you waiting on confirmation from the devs?

**Comment by Davidutro** [comment]
waiting on confirmation from Devs. Trying to sort through it mentally myself. 

I received this answer from Lev. Will work through the implications of that today.

> the way chao phrased his question is confusing
you don't need e in the calculation, no not at all. e only arises when converting from continuous to discrete interest
let r be the per-second interest rate, e.g. interest of 0.1% per second is r = 1.001, then the stability fee on a initial debt of d after n seconds is calculated as (r ^ n - 1) * d. It's that simple, there's nothing else to it.

**Comment by Chaology** [comment]
> waiting on confirmation from Devs. Trying to sort through it mentally myself.
> 
> I received this answer from Lev. Will work through the implications of that today.
> 
> > the way chao phrased his question is confusing
> > you don't need e in the calculation, no not at all. e only arises when converting from continuous to discrete interest
> > let r be the per-second interest rate, e.g. interest of 0.1% per second is r = 1.001, then the stability fee on a initial debt of d after n seconds is calculated as (r ^ n - 1) * d. It's that simple, there's nothing else to it.

I think that aligns with my case of removing _e_. Let's wait for the confirmation from Devs though.

**Comment by Davidutro** [comment]
I took a break from dealing with this. Basically, here is what Lev said

image

**Comment by Davidutro** [comment]
I will take a look at how we should edit this FAQ later today.

**Comment by Davidutro** [comment]
We decided to keep the Stability Fee FAQ the same as it is now. We will update it for the MCD launch.

Although the SF FAQ is not perfect in describing how the SF works we can do the work of adequately describing it for MCD.

**Pull request closed without merging**
